apiVersion: bluebrown.github.io/v1alpha1
kind: KubeAudit
metadata:
  name: security
  annotations:
    config.kubernetes.io/local-config: "true"
# the spec is identical to the kubeaudit config file
# https://github.com/Shopify/kubeaudit#configuration-file
spec:
  # by default all auditors are enabled
  enabledAuditors: {}
  # specific auditor configs
  auditors:
    limits:
      cpu: "750m"
      memory: "500m"
