apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd-minimal
images:
- name: quay.io/argoproj/argocd
  newTag: v2.6.1
resources:
- https://github.com/argoproj/argo-cd//manifests/crds?ref=v2.6.1
- https://github.com/argoproj/argo-cd//manifests/cluster-rbac?ref=v2.6.1
- https://github.com/argoproj/argo-cd//manifests/base/config?ref=v2.6.1
- https://github.com/argoproj/argo-cd//manifests/base/redis?ref=v2.6.1
- https://github.com/argoproj/argo-cd//manifests/base/repo-server?ref=v2.6.1
- https://github.com/argoproj/argo-cd//manifests/base/server?ref=v2.6.1
- https://github.com/argoproj/argo-cd//manifests/base/application-controller?ref=v2.6.1
