apiVersion: bluebrown.github.io/v1alpha1
kind: KubeConformValidator
metadata:
  name: schema-validation
  annotations:
    config.kubernetes.io/local-config: "true"
    config.kubernetes.io/function: |
      container:
        image: bluebrown/krm-filter/kubeconform
data:
  strict: true
---
apiVersion: bluebrown.github.io/v1alpha1
kind: KubeAuditValidator
metadata:
  name: validate
  annotations:
    config.kubernetes.io/local-config: "true"
    config.kubernetes.io/function: |
      container:
        image: bluebrown/krm-filter/kubeaudit
spec:
  enabledAuditors:
    apparmor: false # kind has no appamor
