apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./localized-argocd/
components:
- ./components/cmp-sidecar/
- ./components/aad-token/
- ./components/argocd-kustomize/
transformers:
- ./_filters.yaml
- ./_validators.yaml
# validators: [./_validators.yaml] # bug
secretGenerator:
- name: git-repo
  options:
    disableNameSuffixHash: true
    labels:
      argocd.argoproj.io/secret-type: repository
  literals:
  - type=git
  - name=krm-filter
  - url=https://github.com/bluebrown/krm-filter
  - project=default
  envs:
  - ./etc/git-creds.env # should contain 'username' and 'password'
